spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?sslmode=${DB_SSLMODE:prefer}&currentSchema=${DB_SCHEMA:managehw}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  thymeleaf:
    cache: true
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  shutdown: graceful
  forward-headers-strategy: framework
  compression:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
