-- PostgreSQL 17 물리 스키마 초안
-- 기준: docs/refdoc/db.txt (Flyway 미적용 검토본)

CREATE TABLE common_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL,
    code_name varchar(100) NOT NULL,
    description varchar(500),
    remark varchar(500),
    sort_order integer NOT NULL DEFAULT 0,
    hierarchy_level smallint NOT NULL DEFAULT 1,
    parent_code_id bigint,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_common_codes_code UNIQUE (code),
    CONSTRAINT fk_common_codes_parent FOREIGN KEY (parent_code_id)
        REFERENCES common_codes (id) ON DELETE RESTRICT,
    CONSTRAINT ck_common_codes_code_not_blank CHECK (btrim(code) <> ''),
    CONSTRAINT ck_common_codes_name_not_blank CHECK (btrim(code_name) <> ''),
    CONSTRAINT ck_common_codes_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_common_codes_hierarchy CHECK (hierarchy_level >= 1),
    CONSTRAINT ck_common_codes_not_self_parent CHECK (parent_code_id IS NULL OR parent_code_id <> id)
);

CREATE INDEX ix_common_codes_parent_sort ON common_codes (parent_code_id, sort_order, id);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    login_id varchar(100) NOT NULL,
    password_hash varchar(100) NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    failed_login_count integer NOT NULL DEFAULT 0,
    locked_until timestamptz,
    last_login_at timestamptz,
    region_code_id bigint,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_role_code FOREIGN KEY (role_code_id)
        REFERENCES common_codes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_users_region_code FOREIGN KEY (region_code_id)
        REFERENCES common_codes (id) ON DELETE RESTRICT,
    CONSTRAINT ck_users_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT ck_users_login_id_not_blank CHECK (btrim(login_id) <> ''),
    CONSTRAINT ck_users_password_hash_not_blank CHECK (btrim(password_hash) <> ''),
    CONSTRAINT ck_users_failed_login_count CHECK (failed_login_count >= 0)
);

CREATE UNIQUE INDEX uq_users_login_id_ci ON users (lower(login_id));
CREATE INDEX ix_users_role_code ON users (role_code_id);
CREATE INDEX ix_users_region_code ON users (region_code_id) WHERE region_code_id IS NOT NULL;

CREATE TABLE parent_student_links (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id bigint NOT NULL,
    student_id bigint NOT NULL,
    status_code_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_parent_student_links_parent FOREIGN KEY (parent_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_parent_student_links_student FOREIGN KEY (student_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_parent_student_links_status_code FOREIGN KEY (status_code_id)
        REFERENCES common_codes (id) ON DELETE RESTRICT,
    CONSTRAINT uq_parent_student_links_pair UNIQUE (parent_id, student_id),
    CONSTRAINT ck_parent_student_links_distinct_users CHECK (parent_id <> student_id)
);

CREATE INDEX ix_parent_student_links_parent_status ON parent_student_links (parent_id, status_code_id);
CREATE INDEX ix_parent_student_links_student_status ON parent_student_links (student_id, status_code_id);

CREATE TABLE subjects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    subject_code_id bigint,
    name varchar(100) NOT NULL,
    description text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_subjects_student FOREIGN KEY (student_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_subjects_subject_code FOREIGN KEY (subject_code_id)
        REFERENCES common_codes (id) ON DELETE RESTRICT,
    CONSTRAINT uq_subjects_id_student UNIQUE (id, student_id),
    CONSTRAINT ck_subjects_name_not_blank CHECK (btrim(name) <> '')
);

CREATE UNIQUE INDEX uq_subjects_student_name_ci ON subjects (student_id, lower(name));
CREATE UNIQUE INDEX uq_subjects_student_code ON subjects (student_id, subject_code_id)
    WHERE subject_code_id IS NOT NULL;

CREATE TABLE homeworks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    subject_id bigint NOT NULL,
    title varchar(200) NOT NULL,
    description text,
    due_date date NOT NULL,
    progress_code_id bigint NOT NULL,
    created_by bigint NOT NULL,
    updated_by bigint NOT NULL,
    deleted_by bigint,
    deleted_at timestamptz,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_homeworks_student FOREIGN KEY (student_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homeworks_subject_student FOREIGN KEY (subject_id, student_id)
        REFERENCES subjects (id, student_id) ON DELETE RESTRICT,
    CONSTRAINT fk_homeworks_progress_code FOREIGN KEY (progress_code_id)
        REFERENCES common_codes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homeworks_created_by FOREIGN KEY (created_by)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homeworks_updated_by FOREIGN KEY (updated_by)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homeworks_deleted_by FOREIGN KEY (deleted_by)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_homeworks_title_not_blank CHECK (btrim(title) <> ''),
    CONSTRAINT ck_homeworks_deletion_state CHECK (
        (is_deleted = false AND deleted_at IS NULL AND deleted_by IS NULL)
        OR (is_deleted = true AND deleted_at IS NOT NULL AND deleted_by IS NOT NULL)
    )
);

CREATE INDEX ix_homeworks_student_due_date_active
    ON homeworks (student_id, due_date, id) WHERE is_deleted = false;
CREATE INDEX ix_homeworks_student_subject_active
    ON homeworks (student_id, subject_id) WHERE is_deleted = false;
CREATE INDEX ix_homeworks_progress_due_date_active
    ON homeworks (student_id, progress_code_id, due_date) WHERE is_deleted = false;

CREATE TABLE homework_histories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    homework_id bigint NOT NULL,
    action_code_id bigint NOT NULL,
    actor_id bigint NOT NULL,
    before_data jsonb,
    after_data jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_homework_histories_homework FOREIGN KEY (homework_id)
        REFERENCES homeworks (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homework_histories_action_code FOREIGN KEY (action_code_id)
        REFERENCES common_codes (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homework_histories_actor FOREIGN KEY (actor_id)
        REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_homework_histories_payload CHECK (before_data IS NOT NULL OR after_data IS NOT NULL)
);

CREATE INDEX ix_homework_histories_homework_created_at
    ON homework_histories (homework_id, created_at, id);

-- 테이블 및 컬럼 논리명
COMMENT ON TABLE common_codes IS '공통코드';
COMMENT ON COLUMN common_codes.id IS '공통코드 식별자';
COMMENT ON COLUMN common_codes.code IS '코드 - 전역 유일 코드(예: ROLE_PARENT, PROGRESS_25)';
COMMENT ON COLUMN common_codes.code_name IS '코드명';
COMMENT ON COLUMN common_codes.description IS '코드설명';
COMMENT ON COLUMN common_codes.remark IS '비고';
COMMENT ON COLUMN common_codes.sort_order IS '순번';
COMMENT ON COLUMN common_codes.hierarchy_level IS '계층';
COMMENT ON COLUMN common_codes.parent_code_id IS '부모코드 식별자';
COMMENT ON COLUMN common_codes.is_active IS '사용여부';
COMMENT ON COLUMN common_codes.created_at IS '생성일시';
COMMENT ON COLUMN common_codes.updated_at IS '수정일시';

COMMENT ON TABLE users IS '사용자';
COMMENT ON COLUMN users.id IS '사용자 식별자';
COMMENT ON COLUMN users.role_code_id IS '역할코드 식별자 - 부모 또는 학생';
COMMENT ON COLUMN users.name IS '사용자명';
COMMENT ON COLUMN users.login_id IS '로그인 아이디';
COMMENT ON COLUMN users.password_hash IS 'BCrypt 비밀번호 해시';
COMMENT ON COLUMN users.is_enabled IS '로그인 가능 여부';
COMMENT ON COLUMN users.failed_login_count IS '연속 로그인 실패 횟수';
COMMENT ON COLUMN users.locked_until IS '계정 잠금 종료 시각';
COMMENT ON COLUMN users.last_login_at IS '마지막 로그인 성공 시각';
COMMENT ON COLUMN users.region_code_id IS '지역코드 식별자 - 법정동 앞 5자리 공통코드';
COMMENT ON COLUMN users.created_at IS '생성일시';
COMMENT ON COLUMN users.updated_at IS '수정일시';

COMMENT ON TABLE parent_student_links IS '역할관계';
COMMENT ON COLUMN parent_student_links.id IS '역할관계 식별자';
COMMENT ON COLUMN parent_student_links.parent_id IS '부모 사용자 식별자';
COMMENT ON COLUMN parent_student_links.student_id IS '학생 사용자 식별자';
COMMENT ON COLUMN parent_student_links.status_code_id IS '관계상태코드 식별자 - 초대, 승인 또는 해제';
COMMENT ON COLUMN parent_student_links.created_at IS '생성일시';
COMMENT ON COLUMN parent_student_links.updated_at IS '수정일시';

COMMENT ON TABLE subjects IS '과목';
COMMENT ON COLUMN subjects.id IS '과목 식별자';
COMMENT ON COLUMN subjects.student_id IS '학생 사용자 식별자';
COMMENT ON COLUMN subjects.subject_code_id IS '과목코드 식별자 - 사용자 정의 과목이면 NULL';
COMMENT ON COLUMN subjects.name IS '과목명';
COMMENT ON COLUMN subjects.description IS '과목설명';
COMMENT ON COLUMN subjects.created_at IS '생성일시';
COMMENT ON COLUMN subjects.updated_at IS '수정일시';

COMMENT ON TABLE homeworks IS '숙제';
COMMENT ON COLUMN homeworks.id IS '숙제 식별자';
COMMENT ON COLUMN homeworks.student_id IS '학생 사용자 식별자';
COMMENT ON COLUMN homeworks.subject_id IS '과목 식별자';
COMMENT ON COLUMN homeworks.title IS '숙제 제목';
COMMENT ON COLUMN homeworks.description IS '숙제 상세내용';
COMMENT ON COLUMN homeworks.due_date IS '숙제 종료일(마감일)';
COMMENT ON COLUMN homeworks.progress_code_id IS '진행률코드 식별자 - 0, 25, 50, 75 또는 100퍼센트';
COMMENT ON COLUMN homeworks.created_by IS '등록 사용자 식별자';
COMMENT ON COLUMN homeworks.updated_by IS '수정 사용자 식별자';
COMMENT ON COLUMN homeworks.deleted_by IS '삭제 사용자 식별자';
COMMENT ON COLUMN homeworks.deleted_at IS '삭제일시';
COMMENT ON COLUMN homeworks.is_deleted IS '삭제여부 - 삭제일시 및 삭제 사용자와 함께 변경';
COMMENT ON COLUMN homeworks.created_at IS '생성일시';
COMMENT ON COLUMN homeworks.updated_at IS '수정일시';

COMMENT ON TABLE homework_histories IS '숙제이력관리';
COMMENT ON COLUMN homework_histories.id IS '숙제이력 식별자';
COMMENT ON COLUMN homework_histories.homework_id IS '숙제 식별자';
COMMENT ON COLUMN homework_histories.action_code_id IS '작업상태코드 식별자 - 생성, 수정 또는 삭제';
COMMENT ON COLUMN homework_histories.actor_id IS '작업 사용자 식별자';
COMMENT ON COLUMN homework_histories.before_data IS '변경전값';
COMMENT ON COLUMN homework_histories.after_data IS '변경후값';
COMMENT ON COLUMN homework_histories.created_at IS '작업일시 - 이력 발생 시각';
