CREATE TABLE homework_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    homework_id bigint NOT NULL,
    content varchar(500) NOT NULL,
    is_completed boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL,
    completed_by bigint,
    completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_homework_tasks_homework FOREIGN KEY (homework_id) REFERENCES homeworks (id) ON DELETE CASCADE,
    CONSTRAINT fk_homework_tasks_completed_by FOREIGN KEY (completed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_homework_tasks_content_not_blank CHECK (btrim(content) <> ''),
    CONSTRAINT ck_homework_tasks_sort_order CHECK (sort_order >= 0),
    CONSTRAINT ck_homework_tasks_completion CHECK (
        (is_completed = true AND completed_by IS NOT NULL AND completed_at IS NOT NULL)
        OR (is_completed = false AND completed_by IS NULL AND completed_at IS NULL)
    )
);

CREATE INDEX ix_homework_tasks_homework ON homework_tasks (homework_id, sort_order, id);

INSERT INTO subjects (student_id, subject_code_id, name, description)
SELECT student.id, subject_code.id, '기타', '서비스 기본 과목'
FROM users student
JOIN common_codes role_code ON role_code.id = student.role_code_id AND role_code.code = 'ROLE_STUDENT'
JOIN common_codes subject_code ON subject_code.code = 'SUBJECT_OTHER'
ON CONFLICT DO NOTHING;

UPDATE homeworks homework
SET subject_id = other_subject.id
FROM subjects current_subject, subjects other_subject
WHERE current_subject.id = homework.subject_id
  AND other_subject.student_id = homework.student_id
  AND other_subject.name = '기타'
  AND current_subject.name NOT IN ('국어', '영어', '수학', '기타');

INSERT INTO homework_tasks (
    homework_id, content, is_completed, sort_order, completed_by, completed_at
)
SELECT homework.id,
       coalesce(nullif(btrim(homework.description), ''), homework.title),
       progress_code.code = 'PROGRESS_100',
       0,
       CASE WHEN progress_code.code = 'PROGRESS_100' THEN homework.updated_by END,
       CASE WHEN progress_code.code = 'PROGRESS_100' THEN homework.updated_at END
FROM homeworks homework
JOIN common_codes progress_code ON progress_code.id = homework.progress_code_id;

COMMENT ON TABLE homework_tasks IS '숙제별 체크 가능한 세부 작업';
COMMENT ON COLUMN homework_tasks.sort_order IS '숙제 안에서 Task가 표시되는 0부터 시작하는 순서';
